rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2

gemfile:
  - test/gemfiles/Gemfile.rails-3.1.x
  - test/gemfiles/Gemfile.rails-3.2.x
  - test/gemfiles/Gemfile.rails-4.0.x

matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: test/gemfiles/Gemfile.rails-4.0.x
    - rvm: 1.9.2
      gemfile: test/gemfiles/Gemfile.rails-4.0.x

notifications:
  email: false
